[package]
name = "fingerd"
version = "0.1.0"
authors = ["Michael Maclean <michael@mgdm.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cap-std = "0.22.0"
getopts = "0.2"
